### ISSUE TITLE
Feature Request: same custom-shaped portals in both dimensions

### ISSUE THREAD

**Issue by steve-the-player** [Roundaround/mc-fabric-nicer-portals#9]
It's a little aggravating to make a cool portal, and then go through and find it a completely different shape on the other side and have to remake it again. When used with Immersive Portals and Pehkui, it can also cause unwanted size changes

**Comment by Roundaround** [comment]
Unfortunately there's a reason even vanilla Minecraft doesn't do this - it's actually very difficult (and computationally expensive!) to find a suitable location for anything bigger than a couple blocks. 99% of the time, this will end up putting any large or weirdly shaped portals on the nether roof because it won't be able to find anywhere inside the cavernous nether to fit it reliably

Secondly Immersive Portals and Pehkui change some game fundamentals quite drastically and trying to work around them is not really something I have the time to take on
